services:
  - type: 'web'
    name: 'swear-jar'
    env: 'ruby'
    buildCommand: 'cd api && bundle install --without test'
    startCommand: 'cd api && bundle exec ruby server.rb'
    envVars:
      - fromGroup: 'swear-jar'
envVarGroups:
- name: 'swear-jar'
  envVars:
  - key: 'BANK_API_KEY'
    sync: false
