services:
  - type: 'web'
    name: 'swear-jar'
    env: 'ruby'
    buildCommand: 'bundle install --without test'
    startCommand: 'bundle exec ruby swear_jar.rb'
    envVars:
      - fromGroup: 'swear-jar'
envVarGroups:
- name: 'swear-jar'
  envVars:
  - key: 'BANK_API_KEY'
    sync: false
