name: 'Test'
on:
  push:
    branches:
      - '**'
jobs:
  test:
    name: 'Test'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Operating System setup'
        run: |
          sudo apt-get update
      - uses: actions/checkout@v2
      - name: 'Checkout'
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git checkout main
          git checkout -
      - name: 'Set up Ruby 2.6.3'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - name: 'Install dependences and test'
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rake test
